### ISSUE TITLE
Albedo affected by postprocessing

### ISSUE THREAD

**Issue by jackjt8** [leMaik/chunky-denoiser#16]
_leMaik 21/04/2020_

> Just drop this line https://github.com/leMaik/chunky-denoiser/blob/master/src/main/java/de/lemaik/chunky/denoiser/BetterRenderManager.java#L144, that will fix both
> We should then post-process the pixels of the denoised image after it is saved, though, right here: https://github.com/leMaik/chunky-denoiser/blob/master/src/main/java/de/lemaik/chunky/denoiser/BetterRenderManager.java#L70

**Comment by leMaik** [comment]
Fixed, but the preview still shows post-processing although the pfm files are _not_ post-processed.
