### ISSUE TITLE
Unpausing a render resets it

### ISSUE THREAD

**Issue by ProNoob135** [leMaik/chunky-denoiser#5]
Paused a render to do something else on my computer, then when I unpaused it, it began re-rendering the normal and albedo (losing the 1k samples I had)

**Comment by leMaik** [comment]
Rendering always starts by rendering albedo and normal maps. You can disable rendering the albedo and normal maps in the _Denoiser_ panel on the left (Chunky 2) or in the _Denoiser_ tab (Chunky 1).

It shouldn't do that after unpausing, though.
